name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Instalação de dependências, testes, construção e deploy.

      - name: Instalação do Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Run Install
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build application
        run: npm run build

      # - name: Create release artifact
      #   run: |

      - name: Deploy para ambiente de testes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
